name: Doctest

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  doctest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build tests
        run: cmake --build build --config Release --target tests

      - name: Run doctest
        run: ./build/source/tests
